"""empty message

Revision ID: 3a7903917cc4
Revises: edc29a59f458
Create Date: 2024-08-13 13:19:39.365322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7903917cc4'
down_revision = 'edc29a59f458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_carts_users_users'), 'users', ['users'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_carts_users_users'), type_='foreignkey')
        batch_op.drop_column('users')

    # ### end Alembic commands ###
