"""empty message

Revision ID: 97b7aea899a8
Revises: 3a7903917cc4
Create Date: 2024-08-13 13:20:26.588364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b7aea899a8'
down_revision = '3a7903917cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_carts_users_users', type_='foreignkey')
        batch_op.drop_column('users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_carts_users_users', 'users', ['users'], ['id'])

    # ### end Alembic commands ###
